version: 2.1

orbs:
  go: circleci/go@3
  ruby: circleci/ruby@2.5.4
  circleci-cli: circleci/circleci-cli@0.1.9

workflows:
  cci-agent-setup:
    jobs:
      - cci-agent-setup:
          context:
            - circleci-agents

jobs:
  cci-agent-setup:
    docker:
      - image: cimg/node:current
    resource_class: medium
    environment:
      SHOULD_BE_PRESENT: "works"
    steps:
      - checkout
      - run:
          name: Hello World
          command: |
            echo "Hello, World!"
            echo $SHOULD_BE_PRESENT
            echo $STEP_ENV
          environment:
            STEP_ENV: "hello from the step"
