version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:24.4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Playwright browsers
          command: npx playwright install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Guardrail: forbid Math.random in tests
          command: |
            if grep -R --include=*.test.* -n "Math\\.random(" src; then
              echo "Found forbidden Math.random() calls in tests. Use mocking instead.";
              exit 1;
            fi
      - run:
          name: Run tests
          command: |
            npm run test
      - store_test_results:
          path: test-results

workflows:
  test-workflow:
    jobs:
      - test
